/*
 This configuration ensures that all log topics are right-padded with spaces to align uniformly on the screen.
 The padding facilitates easy reading and monitoring by ensuring that all messages end at the same column,
 which helps in quickly scanning the log output visually and maintaining a tidy and consistent format on the logger server.
*/
module.exports = {
    START:                                    "○ start                                    ",
    STOP:                                     "○ stop                                     ",
    USER_SKIPPED_BY_LOW_HF:                   "x user_skipped_by_low_hf                   ",
    USER_SKIPPED_BY_HIGH_HF:                  "x user_skipped_by_high_hf                  ",
    USER_SKIPPED_BY_HF:                       "x user_skipped_by_hf                       ",
    USER_SKIPPED_BY_LOW_COLLATERAL:           "x user_skipped_by_collateral               ",
    USER_SKIPPED_BY_LOW_BORROW:               "x user_skipped_by_low_borrow               ",
    USER_ACCEPTED:                            "✓ user_accepted                            ",
    USER_ACCEPTED_BY_HF:                      "✓ user_accepted_by_hf                      ",
    USER_ACCEPTED_BY_HF_AFTER_SIML_RESULT:    "✓ user_accepted_by_hf_after_siml_result    ",
    USER_SKIPPED_BY_FILTERS:                  "x user_skipped_by_filters                  ",
    BORROW_SKIPPED:                           "x borrow_skipped                           ",
    COLLATERAL_SKIPPED:                       "x collateral_skipped                       ",
    BORROW_AND_COLLATERAL_SKIPPED:            "x borrow_and_collateral_skipped            ",
    BORROW_AND_COLLATERAL_ACCEPTED:           "✓ borrow_and_collateral_accepted           ",           
    SIMULATION_PASSED_WITH_STATUS_SUCCESS:    "✓ simulation_passed_with_status_success    ",
    SIMULATION_PASSED_WITH_STATUS_FAILED:     "x simulation_passed_with_status_failed     ",
    SIMULATION_RESULT:                        "○ simulation_result                        ",
    SIMULATION_ERROR:                         "E simulation_error                         ",
    PROVIDER_ERROR:                           "E provider_error                           ",
    USERS_FROM_REDIS_TO_SIMULATION_BY_ASSEST: "✓ users_from_redis_to_simulation_by_asset  ",
    ALL_UNIQUE_USERS_FROM_REDIS_TO_SIMULATION:"✓ all_unique_users_from_redis_to_simulation",
    ALL_USERS_SKIPPED_BY_HF:                  "x all_users_skipped_by_hf                  ",
    LIQUIDATE_EVENT:                          "✓ liquidate_event                          ",
    SIMULATIONS_STARTED:                      "✓ simulations_started                      ",
    INPUT_TRANSMIT:                           "○ input_transmit                           ",
    ERROR_MESSAGE:                            "E error_message                            ",
    RECIEVED_INPUT_ADDRESS:                   "✓ recieved_input_address                   ",
    SEND_USER_TO_DATA_FETCHER:                "✓ send_user_to_data_fetcher                ",
    SEND_DRAIN_EVENT:                         "✓ send_drain_event                         ",
}
